Fix errors due to renamed cops
When running rubocop using gnar-style on a new application I got the
following errors:

```
Error: The `Layout/AlignArguments` cop has been renamed to
`Layout/ArgumentAlignment`.
(obsolete configuration found in
/Users/michaelstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gnar-style-0.8.0/rubocop/rubocop.yml,
please update it)
The `Layout/AlignParameters` cop has been renamed to
`Layout/ParameterAlignment`.
(obsolete configuration found in
/Users/michaelstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gnar-style-0.8.0/rubocop/rubocop.yml,
please update it)
The `Layout/IndentFirstArrayElement` cop has been renamed to
`Layout/FirstArrayElementIndentation`.
(obsolete configuration found in
/Users/michaelstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gnar-style-0.8.0/rubocop/rubocop.yml,
please update it)
```

This commit changes the cop names to fix those errors.